[target.x86_64-unknown-linux-gnu]
# Use static linking for OpenSSL on Linux
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# Force static linking of OpenSSL
OPENSSL_STATIC = "1"
OPENSSL_DIR = "/usr"